### PR TITLE
feat: add API for returning PNG pixels data

### PR DESCRIPTION
**Pull request by yisibl**

### CODE REVIEW

**Comment by jstarpl** [comment]
Is there any help that one can provide to get this PR merged?

**Comment by zimond** [comment]
It would be better if renamed as `pixels`

**Comment by yisibl** [comment]
@jstarpl Now I have finished this PR. 

By the way, what is your usage scenario for this API?

**Comment by yisibl** [comment]
> It would be better if renamed as `pixels`

Thanks, is done.

**Comment by jstarpl** [comment]
> @jstarpl Now I have finished this PR. 
> 
> By the way, what is your usage scenario for this API?

I was hoping to use it to render UI SVGs to pipe them to a Stream Deck display and that accepts an RGB blob, so going through encoding+decoding a PNG is an unnecessary step.

**Pull request merged**
