### PR TITLE
fix: the `defaultFontFamily` not working

### PR DESCRIPTION
**Pull request by yisibl**
Fixed: https://github.com/yisibl/resvg-js/issues/207

## Test

```shell
npm i
npm run build
node example/text.js
```

### CODE REVIEW

**Comment by yisibl** [comment]
@RazrFalcon Sorry for pinging you here, can you help to see why the default font family can't be loaded after splitting into [usvg-text-layout](https://github.com/RazrFalcon/resvg/commit/910ed0109f4e5af4f556414eb2af812ce49f7d7c#diff-1a8520ff3089374420ca8b4c14b6e36f69c27185df4235a7528018cc74e7a332R7)?

**Comment by RazrFalcon** [comment]
What are you using it for? Maybe this would help https://github.com/RazrFalcon/resvg/issues/566

**Comment by yisibl** [comment]
@RazrFalcon I found that it is indeed related to https://github.com/RazrFalcon/resvg/issues/566. The main change I think is caused here: 

https://github.com/RazrFalcon/resvg/commit/36b0e0b928015ef0788a9d0babcbc77eaf8f34aa#diff-6d4d24ae259685abf64776b23b1c6e7af8c3a9718591d7db8d092e3b6cbb216fR684-R686

```rust
if families.is_empty() { // Removing this judgment will restore the effect to 0.27.0.
    families.push(state.opt.font_family.clone())
}
```

## Expected

Consider the following SVG: 

### Case 1
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200">
  <text fill="blue" font-family="serif" font-size="120">
    <tspan x="40" y="143">水</tspan>
  </text>
</svg>
```

When the font-family does not exist or is `serif`, resvg-js passes in the specified family name via the `defaultFontFamily` API, and I expect to be able to fallback the Font Family to `Source Han Serif CN Light`. This works fine for `resvg <= 0.27.0`.

```js
const resvg = new Resvg(svg, {
    background: '#fff',
    font: {
      fontFiles: ['./example/SourceHanSerifCN-Light-subset.ttf'], // Load custom fonts.
      loadSystemFonts: false, // It will be faster to disable loading system fonts.
      defaultFontFamily: 'Source Han Serif CN Light',
    },
    logLevel: 'debug', // Default Value: error
  })
```
I've done some debugging, can you help me see what the problem is?

```shell
npm install
npm run build:debug
node example/text.js
```
<details>
<summary>Case 1</summary>

```shell
[2023-02-13T05:33:34Z DEBUG resvg_js::fonts] Loaded 1 font faces in 0.741ms.
[2023-02-13T05:33:34Z DEBUG resvg_js::fonts] Font './example/SourceHanSerifCN-Light-subset.ttf':0 found in 0.016ms.
[/Users/yisibl/resvg/usvg/src/text.rs:677] &families = [
    "serif",
]
[/Users/yisibl/resvg/usvg/src/text.rs:678] &state.opt.font_family = "Source Han Serif CN Light"
[/Users/yisibl/resvg/usvg/src/text.rs:679] &families = [
    "serif",
]
[/Users/yisibl/resvg/usvg/src/text.rs:677] &families = [
    "serif",
]
[/Users/yisibl/resvg/usvg/src/text.rs:678] &state.opt.font_family = "Source Han Serif CN Light"
[/Users/yisibl/resvg/usvg/src/text.rs:679] &families = [
    "serif",
]
[/Users/yisibl/resvg/usvg/src/text.rs:677] &families = [
    "serif",
]
[/Users/yisibl/resvg/usvg/src/text.rs:678] &state.opt.font_family = "Source Han Serif CN Light"
[/Users/yisibl/resvg/usvg/src/text.rs:679] &families = [
    "serif",
]
[/Users/yisibl/resvg/usvg-text-layout/src/lib.rs:509] &span.font.families = [
    "serif",
]
[/Users/yisibl/resvg/usvg-text-layout/src/lib.rs:686] &name_list = [
    Serif,
    Serif,
]
[2023-02-13T05:33:34Z WARN  usvg_text_layout] No match for 'serif' font-family.
[/Users/yisibl/resvg/usvg-text-layout/src/lib.rs:509] resolve_font(&span.font, fontdb) = None
[/Users/yisibl/resvg/usvg-text-layout/src/lib.rs:686] &name_list = [
    Serif,
    Serif,
]
[2023-02-13T05:33:34Z WARN  usvg_text_layout] No match for 'serif' font-family.
```
</details>

### Case 2

Explicitly set font-family to the family name of the actual font

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200">
    <text fill="blue" font-family="Source Han Serif CN Light" font-size="120">
      <tspan x="40" y="143">水</tspan>
    </text>
  </svg>
```

<details>
<summary>Case 2</summary>

```shell
[2023-02-13T05:44:43Z DEBUG resvg_js::fonts] Loaded 1 font faces in 0.131ms.
[2023-02-13T05:44:43Z DEBUG resvg_js::fonts] Font './example/SourceHanSerifCN-Light-subset.ttf':0 found in 0.009ms.
[/Users/yisibl/resvg/usvg/src/text.rs:677] &families = [
    "Source Han Serif CN Light",
]
[/Users/yisibl/resvg/usvg/src/text.rs:678] &state.opt.font_family = "Source Han Serif CN Light"
[/Users/yisibl/resvg/usvg/src/text.rs:679] &families = [
    "Source Han Serif CN Light",
]
[/Users/yisibl/resvg/usvg/src/text.rs:677] &families = [
    "Source Han Serif CN Light",
]
[/Users/yisibl/resvg/usvg/src/text.rs:678] &state.opt.font_family = "Source Han Serif CN Light"
[/Users/yisibl/resvg/usvg/src/text.rs:679] &families = [
    "Source Han Serif CN Light",
]
[/Users/yisibl/resvg/usvg/src/text.rs:677] &families = [
    "Source Han Serif CN Light",
]
[/Users/yisibl/resvg/usvg/src/text.rs:678] &state.opt.font_family = "Source Han Serif CN Light"
[/Users/yisibl/resvg/usvg/src/text.rs:679] &families = [
    "Source Han Serif CN Light",
]
[/Users/yisibl/resvg/usvg-text-layout/src/lib.rs:509] &span.font.families = [
    "Source Han Serif CN Light",
]
[/Users/yisibl/resvg/usvg-text-layout/src/lib.rs:686] &name_list = [
    Name(
        "Source Han Serif CN Light",
    ),
    Serif,
]
[/Users/yisibl/resvg/usvg-text-layout/src/lib.rs:509] resolve_font(&span.font, fontdb) = Some(
    ResolvedFont {
        id: ID(
            2,
        ),
        units_per_em: 2048,
        ascent: 2357,
        descent: -586,
        x_height: 1053,
        underline_position: -307,
        underline_thickness: 102,
        line_through_position: 631,
        subscript_offset: 154,
        superscript_offset: 717,
    },
)
[/Users/yisibl/resvg/usvg-text-layout/src/lib.rs:686] &name_list = [
    Name(
        "Source Han Serif CN Light",
    ),
    Serif,
]
```
</details>

**Comment by RazrFalcon** [comment]
You must not use/rely on `Options::font_family` to begin with. It is used as a worst case fallback. An SVG must define `font-family`, otherwise an SVG library can do whatever it wants.

In short, as the linked issue noted, the rules are simple: `Options::font_family` used only when there are no `font-family` property anywhere in the file.

In case of your file, you do define family as `font-family="serif"`, meaning you have to set `fontdb::Database::set_serif_family` and not `Options::font_family`

The previous behavior wasn't technically correct.

**Review by zimond — APPROVED** [review]

**Comment by yisibl** [comment]
@RazrFalcon Yes, I'm using `set_serif_family`, I just need to determine if `defaultFontFamily` exists. See https://github.com/yisibl/resvg-js/pull/208/commits/ed4c8502c0ec63096b92e5ce4d550aa3614b7711#diff-48b59335e054ce050f464a700ccd2a85bf1c4f203216f82ee487f2da42985bf3

**Pull request merged**
