### PR TITLE
chore: upgrade to resvg/usvg 0.25

### LINKED ISSUE #155: Library is cutting the corners of SVG
This is my original SVG:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-0.125 -0.125 24.25 24.25" stroke-width="1.75" height="400" width="400"><defs></defs><title>desktop-monitor-approve</title><path d="M23.25,6.75a6,6,0,1,1-6-6" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></path><path d="M23.25,2.25,17.78,7.719a.749.749,0,0,1-1.06,0L15,6" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></path><polygon points="15.75 23.25 8.25 23.25 9 20.25 15 20.25 15.75 23.25" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></polygon><line x1="6" y1="23.25" x2="18" y2="23.25" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></line><line x1="0.75" y1="17.25" x2="23.25" y2="17.25" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></line><path d="M23.25,14.25v3a3,3,0,0,1-3,3H3.75a3,3,0,0,1-3-3V6.75a3,3,0,0,1,3-3h4.5" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></path></svg>
```
- Preview: 
Screenshot 2022-10-19 at 12 51 16 PM

After render SVG as PNG the library is cutting one of the corners
#### Result ->
Screenshot 2022-10-19 at 12 56 43 PM

You can check the base64 version of the image here 
[image.txt](https://github.com/yisibl/resvg-js/files/9823069/image.txt)

I tested changing render values but nothing works.

### PR DESCRIPTION
**Pull request by zimond**
closes #155 #138

### CODE REVIEW

**Comment by cbrwizard** [comment]
Eagerly waiting for this to be merged and a new release to be published :) this will help with a bugfix in our Streamline product

**Comment by yisibl** [comment]
Thanks!

**Comment by andirsun** [comment]
@yisibl Hey! are you planning to release a new version with this fix soon ?

**Comment by yisibl** [comment]
I'm sorry, I've been busy with work lately. I will do my best to release the new version this weekend.

**Pull request merged**
