### PR TITLE
feat: add wasm file to exports

### PR DESCRIPTION
**Pull request by hadeeb**
require.resolve and bundlers like vite are unable to resolve the wasm file.

Cheers

### CODE REVIEW

**Comment by yisibl** [comment]
Thanks!

Does vite have documentation for this?

**Comment by hadeeb** [comment]
It's not specific to vite.

```js
// if using "type":"module"
// import { createRequire } from "module";
// const require = createRequire(import.meta.url);

try {
  // This works
  const indexFile = require.resolve("@resvg/resvg-wasm");
  console.log({ indexFile });
  // This does not work
  const wasmFile = require.resolve("@resvg/resvg-wasm/index_bg.wasm");
  console.log({ wasmFile });
} catch (error) {
  console.error({ error });
}

```

this code works after adding the wasm file to exports.


From [nodejs.org](https://nodejs.org/api/packages.html#package-entry-points)
> Existing packages introducing the ["exports"](https://nodejs.org/api/packages.html#exports) field will prevent consumers of the package from using any entry points that are not defined, including the [package.json](https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions) (e.g. require('your-package/package.json'). This will likely be a breaking change.

**Comment by yisibl** [comment]
Can you add a test case?

**Comment by yisibl** [comment]
Thank you very much, let's merge it first.

**Comment by jeetiss** [comment]
@yisibl I got the same error with webpack! Could you please release this patch?

```
Module not found: Package path ./index_bg.wasm is not exported from package
/playground/node_modules/@resvg/resvg-wasm (see exports field in
/playground/node_modules/@resvg/resvg-wasm/package.json)
```

**Comment by yisibl** [comment]
@jeetiss Done https://github.com/yisibl/resvg-js/releases/tag/v2.3.0

**Pull request merged**
